fruits=[]
a=input("Enter first fruit name\n")
fruits.append(a)
b=input("Enter first fruit name\n")
fruits.append(b)
c=input("Enter first fruit name\n")
fruits.append(c)
d=input("Enter first fruit name\n")
fruits.append(d)
e=input("Enter first fruit name\n")
fruits.append(e)
f=input("Enter first fruit name\n")
fruits.append(f)
g=input("Enter first fruit name\n")
fruits.append(g)
print(fruits)