marks=[]
a=int(input("Enter subject marks\n"))
marks.append(a)
b=int(input("Enter subject marks\n"))
marks.append(b)
c=int(input("Enter subject marks\n"))
marks.append(c)
d=int(input("Enter subject marks\n"))
marks.append(d)
print(marks)
marks.sort()
print(marks)