s=set()
a=int(input("Enter the number a"))
b=int(input("Enter the number b"))
c=int(input("Enter the number c"))
d=int(input("Enter the number d"))
e=int(input("Enter the number e"))
f=int(input("Enter the number f"))
g=int(input("Enter the number g"))
h=int(input("Enter the number h"))
s.add(a)
s.add(b)
s.add(c)
s.add(d)
s.add(e)
s.add(f)
s.add(g)
s.add(h)
print(s)
